/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as ThesesRouteImport } from './routes/theses'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PotRouteImport } from './routes/pot'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OrbPreviewRouteImport } from './routes/orb-preview'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const AgentsLazyRouteImport = createFileRoute('/agents')()

const AgentsLazyRoute = AgentsLazyRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/agents.lazy').then((d) => d.Route))
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ThesesRoute = ThesesRouteImport.update({
  id: '/theses',
  path: '/theses',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PotRoute = PotRouteImport.update({
  id: '/pot',
  path: '/pot',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbPreviewRoute = OrbPreviewRouteImport.update({
  id: '/orb-preview',
  path: '/orb-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/journal': typeof JournalRoute
  '/orb-preview': typeof OrbPreviewRoute
  '/portfolio': typeof PortfolioRoute
  '/pot': typeof PotRoute
  '/settings': typeof SettingsRoute
  '/theses': typeof ThesesRoute
  '/trade': typeof TradeRoute
  '/agents': typeof AgentsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/journal': typeof JournalRoute
  '/orb-preview': typeof OrbPreviewRoute
  '/portfolio': typeof PortfolioRoute
  '/pot': typeof PotRoute
  '/settings': typeof SettingsRoute
  '/theses': typeof ThesesRoute
  '/trade': typeof TradeRoute
  '/agents': typeof AgentsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/journal': typeof JournalRoute
  '/orb-preview': typeof OrbPreviewRoute
  '/portfolio': typeof PortfolioRoute
  '/pot': typeof PotRoute
  '/settings': typeof SettingsRoute
  '/theses': typeof ThesesRoute
  '/trade': typeof TradeRoute
  '/agents': typeof AgentsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/journal'
    | '/orb-preview'
    | '/portfolio'
    | '/pot'
    | '/settings'
    | '/theses'
    | '/trade'
    | '/agents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/journal'
    | '/orb-preview'
    | '/portfolio'
    | '/pot'
    | '/settings'
    | '/theses'
    | '/trade'
    | '/agents'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/journal'
    | '/orb-preview'
    | '/portfolio'
    | '/pot'
    | '/settings'
    | '/theses'
    | '/trade'
    | '/agents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  JournalRoute: typeof JournalRoute
  OrbPreviewRoute: typeof OrbPreviewRoute
  PortfolioRoute: typeof PortfolioRoute
  PotRoute: typeof PotRoute
  SettingsRoute: typeof SettingsRoute
  ThesesRoute: typeof ThesesRoute
  TradeRoute: typeof TradeRoute
  AgentsLazyRoute: typeof AgentsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theses': {
      id: '/theses'
      path: '/theses'
      fullPath: '/theses'
      preLoaderRoute: typeof ThesesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pot': {
      id: '/pot'
      path: '/pot'
      fullPath: '/pot'
      preLoaderRoute: typeof PotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orb-preview': {
      id: '/orb-preview'
      path: '/orb-preview'
      fullPath: '/orb-preview'
      preLoaderRoute: typeof OrbPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  JournalRoute: JournalRoute,
  OrbPreviewRoute: OrbPreviewRoute,
  PortfolioRoute: PortfolioRoute,
  PotRoute: PotRoute,
  SettingsRoute: SettingsRoute,
  ThesesRoute: ThesesRoute,
  TradeRoute: TradeRoute,
  AgentsLazyRoute: AgentsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
